version: '3.8'

services:
  ekapack:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_php
    restart: unless-stopped
    working_dir: /var/www/html
    environment:
      B_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: laravel
      DB_USERNAME: laravel
      DB_PASSWORD: password
    volumes:
      - .:/var/www/html
    networks:
      - ekapack-laravel

  ekapack_nginx:
    image: nginx:alpine
    container_name: nginx_server
    restart: unless-stopped
    ports:
      - "8077:80"
    volumes:
      - ./:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - ekapack
    networks:
      - ekapack-laravel

  ekapack_postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - ekapack-laravel

  ekapack_queue:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_queue
    restart: unless-stopped
    command: php artisan queue:work --sleep=3 --tries=3 --timeout=90
    volumes:
      - .:/var/www/html
    depends_on:
      - ekapack
    networks:
      - ekapack-laravel

volumes:
  pgdata:

networks:
  ekapack-laravel: